-- Seed data migrated from the hardcoded `jobs` array that used to live
-- in src/components/CareersPage.jsx. All 8 are marked published (1) to
-- preserve current site behavior exactly. Run after schema.sql.

INSERT INTO jobs (title, department, location, experience, work_mode, about, responsibilities, requirements, is_published, created_at, updated_at)
VALUES
  ('AI/ML Engineer', 'Engineering', 'Noida', 'Senior (5+ yrs)', 'On-site', 'Evoletrix is seeking a production-focused AI/ML Engineer to design, build, and deploy robust machine learning models and intelligent agentic architectures. You will take charge of our AI capabilities from model selection to secure API delivery.', '["Design, train, and optimize deep learning algorithms for client workflows.", "Implement high-performance Retrieval-Augmented Generation (RAG) search engines.", "Integrate autonomous agentic pipelines to automate complex data processing tasks.", "Work closely with DevOps to deploy models inside containerized GPU servers."]', '["3+ years of professional machine learning development experience.", "Strong proficiency in Python, PyTorch/TensorFlow, and Hugging Face library.", "Deep familiarity with vector databases (Pinecone, pgvector) and embeddings.", "Experience optimizing model latency and memory footprints in cloud setups."]', 1, NOW(), NOW()),
  ('Tech Lead Node.js', 'Engineering', 'Noida', 'Senior (5+ yrs)', 'Hybrid', 'We are looking for a hands-on Tech Lead to architect and optimize our Node.js microservices. You will guide backend engineering standards, enforce database reliability, and mentor a talented engineering team.', '["Architect and maintain highly scalable RESTful and GraphQL API servers.", "Manage SQL and NoSQL database schemas, queries, and optimization strategies.", "Oversee security compliance, authentication tokens, and rate limiters.", "Review pull requests and enforce test coverage, clean code patterns, and speed profiles."]', '["6+ years of professional backend development with Node.js and Express.", "Expertise in PostgreSQL/MySQL query tuning and index management.", "Familiarity with Redis caching, Docker containerization, and AWS hosting.", "Exceptional technical leadership and communication capabilities."]', 1, NOW(), NOW()),
  ('Social Media Executive', 'Marketing', 'Noida', 'Junior (1-3 yrs)', 'On-site', 'Join our growth squad to amplify Evoletrix`s brand presence across digital networks. You will translate complex software projects and engineering stories into engaging, reader-friendly content.', '["Curate, schedule, and moderate visual content on LinkedIn, X (Twitter), and tech forums.", "Analyze traffic data and campaign conversions to optimize community outreach.", "Collaborate with developers and UI designers to draft informative carousel slide decks."]', '["1-3 years of marketing or social media management experience.", "Exceptional copywriting skills with an eye for technical storytelling.", "Familiarity with visual design tools like Figma or Canva.", "Prior experience in B2B SaaS or technical consultancy agencies is a huge plus."]', 1, NOW(), NOW()),
  ('Full Stack Developer', 'Engineering', 'Faridabad', 'Mid-level (3-5 yrs)', 'Hybrid', 'We are looking for a versatile Full Stack Developer to build interactive client dashboards. You will bridge frontend interfaces with server-side microservices.', '["Implement pixel-perfect UI screens in React.js and Tailwind CSS.", "Develop backend endpoint logic, data validations, and database hooks in Node.js.", "Write comprehensive unit tests and optimize website core vitals."]', '["3+ years of full-stack engineering experience.", "Advanced command of JavaScript/TypeScript, React.js, Node.js, and CSS.", "Experience utilizing PostgreSQL or MongoDB database architectures.", "Familiarity with Git branching and Vercel/Render deployments."]', 1, NOW(), NOW()),
  ('Senior UI/UX Designer', 'Design', 'Noida', 'Senior (5+ yrs)', 'Remote', 'Evoletrix is seeking a Senior UI/UX Designer to craft premium product mockups and design tokens for digital portals. You will lead client design discovery sessions.', '["Define typography, spacing grids, and component libraries inside Figma.", "Design wireframes, high-fidelity mockups, and interactive prototypes.", "Collaborate with developers to align CSS styling with the original layouts."]', '["5+ years of digital product UI/UX design experience.", "Outstanding design portfolio showcasing clean, grid-based typography.", "Advanced proficiency in Figma, design systems, and responsive layouts."]', 1, NOW(), NOW()),
  ('DevOps Architect', 'Engineering', 'Noida', 'Senior (5+ yrs)', 'Remote', 'Scale and secure our cloud infrastructure. You will optimize CI/CD pipelines, coordinate deployments, and audit environment security.', '["Build and monitor containerized cluster stacks in AWS and GCP.", "Optimize automated Git actions, unit testing triggers, and static checking.", "Configure CDN layers, firewalls, and server encryption standards."]', '["5+ years of DevOps or Cloud infrastructure experience.", "Excellent command of Docker, Terraform, Kubernetes, and GitHub Actions.", "Deep familiarity with server security audits and hosting cost control."]', 1, NOW(), NOW()),
  ('GIS Specialist', 'Engineering', 'Faridabad', 'Mid-level (3-5 yrs)', 'On-site', 'Work inside our mapping team to coordinate spatial database indexing and render high-resolution raster files on interactive maps.', '["Manage, clean, and convert geospatial data projections (raster and shapefiles).", "Write and optimize PostGIS queries and custom Python geoprocessing algorithms.", "Integrate geofences and maps into frontend React dashboards via Mapbox APIs."]', '["3+ years of experience working with GIS tools and databases.", "Strong capabilities in PostGIS, Python (GDAL, Shapely), and JavaScript maps.", "Excellent grasp of coordinates, geodetic projections, and coordinate datums."]', 1, NOW(), NOW()),
  ('Product Manager', 'Product Management', 'Remote', 'Senior (5+ yrs)', 'Remote', 'Evoletrix is seeking a Product Manager to translate business goals into sprint milestones. You will coordinate with developers and report progress to stakeholders.', '["Define detailed product scopes, specifications, and backlog milestones.", "Lead client alignment calls, prioritize tasks, and resolve team blockers.", "Validate user flows and coordinate launch strategies."]', '["5+ years of software product management experience.", "Strong technical understanding of APIs, data flow, and frontend components.", "Outstanding documentation, task tracking, and communication habits."]', 1, NOW(), NOW());
